spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssgl?serverTimezone=UTC&useSSL=true
    username: root
    password: zyy1103..
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .html
mybatis-plus:
  type-aliases-package: com.road.bean
  configuration:
    map-underscore-to-camel-case: true

myredis:
  url: localhost
  port: 6379
  password: dreamBuilding2022..
server:
  port: 80

rocketmq:
  producer:
    group: springBootGroup
  name-server: 127.0.0.1:9876